version: '3'
services:
  reactioncommerce:
    image: reactioncommerce/reaction:latest
    ports:
    - 8080:3000
    links:
    - mongo
    environment:
    - ROOT_URL=http://localhost
    - MONGO_URL=mongodb://mongo:27017/reactioncommerce
    - REACTION_EMAIL=you@example.com
    - REACTION_USER=admin
    - REACTION_AUTH=password

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod --storageEngine=wiredTiger
